// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForInsertBulkMessages implements pgx.CopyFromSource.
type iteratorForInsertBulkMessages struct {
	rows                 []InsertBulkMessagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBulkMessages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBulkMessages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].NameFrom,
		r.rows[0].NameTo,
		r.rows[0].Message,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForInsertBulkMessages) Err() error {
	return nil
}

func (q *Queries) InsertBulkMessages(ctx context.Context, arg []InsertBulkMessagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"messages"}, []string{"name_from", "name_to", "message", "created_at"}, &iteratorForInsertBulkMessages{rows: arg})
}
