// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int32
	NameFrom  string
	NameTo    string
	Message   string
	CreatedAt pgtype.Timestamp
}
